# Generated by Django 4.2.7 on 2023-11-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_baseprofile_remove_user_profile_seekerprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shelterprofile",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelter_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
