# Generated by Django 5.0 on 2023-12-09 04:56

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_baseprofile_user_seekerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=accounts.helpers.RandomFileName('profile_images/')),
        ),
    ]
