databases:
  - name: petpal
    databaseName: petpal-db
    user: petpal

services:
  - type: web
    name: petpal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn petpal.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4