# Generated by Django 5.0 on 2023-12-09 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_baseprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='available', max_length=200)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_listings', to='accounts.shelterprofile')),
            ],
        ),
    ]
