# Generated by Django 4.2.8 on 2023-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
