# Generated by Django 4.2.8 on 2023-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='breed',
            field=models.CharField(default='corgi', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='size',
            field=models.IntegerField(),
        ),
    ]
