# Generated by Django 4.2.8 on 2023-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petmodel_age_alter_petmodel_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='colour',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
