# Generated by Django 4.2.8 on 2023-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_petmodel_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='colour',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('grey', 'Grey'), ('blonde', 'Blonde'), ('orange', 'Orange'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
