# Generated by Django 5.0 on 2023-12-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='previous_experience',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_pets',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
